imports:
- path: sap_hana.py
- path: hana_deployment.py

resources:
- name: hana_deployment
  type: hana_deployment.py
  properties:
    environment: test

- name: sap_hana
  type: sap_hana.py
  properties:
    instanceName: sandbox-303kdn50-test-hana-vm
    instanceType: n1-highmem-32
    zone: europe-west4-c
    subnetwork: default
    linuxImage: family/sles-12-sp2-sap
    linuxImageProject: suse-sap-cloud
    sap_hana_deployment_bucket: sandbox-303kdn50-saprepo
    sap_hana_sid: ABC
    sap_hana_instance_number: 00
    sap_hana_sidadm_password: Google123
    sap_hana_system_password: Google123
    sap_hana_scaleout_nodes: 1
